# -----------------------------------------------------------------------------
# FILE: wrangler.toml
#
# DESCRIPTION:
# This file configures the WAFu project. It includes all necessary bindings
# for Durable Objects, KV, Services, and the cron trigger for scheduled tasks.
# -----------------------------------------------------------------------------

name = "wafu"
main = "src/worker.js"
compatibility_date = "2025-07-31"

# --- Static Asset Serving ---
# This replaces the deprecated `[[site]]` configuration. It tells Wrangler
# to bundle the contents of the "./public" directory with the worker.
assets = "public"


# --- Environment Variables ---
# These variables are accessible inside the Worker at `env.VARIABLE_NAME`
[vars]
# This secret is the master password for the admin to log in.
# It should be set via the command line for security:
# `wrangler secret put WAFU_ADMIN_SECRET`
WAFU_ADMIN_SECRET = "your-super-secret-admin-password"

# This secret is used to sign and verify all JWTs (for both admin and OTP sessions).
# It should also be set via the command line:
# `wrangler secret put JWT_SECRET`
JWT_SECRET = "your-strong-jwt-signing-secret"


[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["GlobalRulesDO", "RouteRulesDO", "OtpDO", "EventLogsDO", "AuditLogsDO"]

# --- Durable Object Bindings ---
# The bindings now need to be defined individually.
[[durable_objects.bindings]]
name = "WAFU_GLOBAL_DO"
class_name = "GlobalRulesDO"

[[durable_objects.bindings]]
name = "WAFU_ROUTE_DO"
class_name = "RouteRulesDO"

[[durable_objects.bindings]]
name = "WAFU_OTP_DO"
class_name = "OtpDO"

[[durable_objects.bindings]]
name = "WAFU_EVENT_LOGS_DO"
class_name = "EventLogsDO"

[[durable_objects.bindings]]
name = "WAFU_AUDIT_LOGS_DO"
class_name = "AuditLogsDO"


# --- KV Namespace Bindings ---
[[kv_namespaces]]
binding = "WAFU_LOOKUP_TABLES"
id = "YOUR_KV_NAMESPACE_ID_HERE"

# --- Service Bindings ---
[[services]]
binding = "SELF"
service = "wafu"

[[services]]
binding = "MY_API_WORKER"
service = "my-api-worker"

# --- Scheduled Worker Trigger ---
[triggers]
crons = ["*/15 * * * *"]


